# -*- coding: utf-8 -*-
# Plantilles del manual (revisades 4/10/2026): (nom, cost, dif, lat, paràmetres, opcions)
T = [
 ('Autometge', 15, 2, None, [('narratiu',), ('durada',), ('autoeina', 5)], {}),
 ('Bastó neural', 10, None, None, [('arma', 'contundent', 2, 2), ('estat', 'atordit', 0), ('estat', 'lent', 2)], {}),
 ('Botes antigravetat', 13, 1, 1, [('usuari',), ('durada',), ('tret', 'levitar', 15)], {}),
 ('Ciberbraç', 22, None, 2, [('usuari',), ('armadura', 2), ('eina', 3), ('eina2', 3)], {'permanent': True}),
 ('Cibermòdem', 9, 1, 1, [('usuari',), ('durada',), ('eina', 3)], {}),
 ("Cibermòdem d'interfície neural", 15, 1, 1, [('usuari',), ('durada',), ('eina', 5)], {}),
 ("Espasa d'energia", 21, None, None, [('arma', 'espasa', 1, 2), ('dany', 'directe', 6, 'ferides'), ('acumulador', 3), ('recàrrega', 11), ('espera',)], {}),
 ('Espasa pretoriana de Terra', 40, None, None, [('arma', 'fulla llarga', 2, 4), ('eina', 5), ('ègida', 9), ('estat', 'sagnant', 3)], {}),
 ('Espasa serra', 11, None, None, [('arma', 'espasa', 2, 4), ('estat', 'sagnant', 3)], {}),
 ('Generador compacte de bretxa', 53, 4, 10, [('complexa',), ('àrea',), ('durada',), ('translocació', 'portals', 'multiversal'), ('recàrrega', 26), ('espera',)], {}),
 ('Guant de Força', 12, None, None, [('arma', 'de mà', 0, 4), ('dany', 'indirecte', 0, 'electricitat'), ('estat', 'atordit', 0)], {}),
 ('Holocapa', 21, None, None, [('armadura base', 'lleugera flexible', 0, 3), ('eina', 2), ('eina2', 2)], {'permanent': True}),
 ('Martell de descàrrega', 15, None, None, [('arma', 'contundent', 2, 5), ('dany', 'indirecte', 0, 'electricitat'), ('estat', 'atordit', 0), ('estat', 'llançat', 0)], {}),
 ("Servoarmadura d'assalt", 62, None, None, [('armadura base', 'pesant', 0, 10), ('atribut', 3), ('eina', 3), ('eina2', 4)], {'permanent': True}),
 ('Sonda neural', 20, 3, None, [('complexa',), ('durada',), ('mental', 'llegir'), ('mental', 'projectar'), ('mental', 'suggestió')], {}),
 ('Tornavís sònic', 31, 2, 4, [('autoeina', 8)], {}),
 ('Ulleres intel·ligents', 13, 2, 4, [('trivial',), ('recàrrega', 5), ('atribut', 1), ('eina', 2), ('eina2', 2)], {}),
 ('Vestit lleuger de reconeixement', 59, None, None, [('armadura base', 'lleugera rígida', -1, 3), ('eina', 3), ('eina2', 3), ('atribut', 2), ('tret', 'levitar', 15)], {'permanent': True}),
 ('Auguris', 10, 2, None, [('ritual',), ('narratiu',), ('durada',), ('il·lusió', 0), ('tret', 'oracle', 30)], {}),
 ('Barrera antimàgia', 21, 1, 10, [('ritual',), ('àrea',), ('durada',), ('barrera', 8)], {}),
 ('Benedicció del fanàtic', 12, 3, 3, [('durada',), ('estat', 'berserc', 0), ('tret', 'dur de pelar', 15)], {}),
 ('Calma', 20, 1, 10, [('ritual',), ('àrea',), ('durada',), ('mental', 'control emocional')], {}),
 ('Cercle de protecció', 14, 1, None, [('ritual',), ('narratiu',), ('àrea',), ('durada',), ('barrera', 12)], {}),
 ('Exorcisme', 17, 1, None, [('ritual',), ('narratiu',), ('distància',), ('durada',), ('mental', 'suggestió'), ('eina', 4)], {}),
 ('Guarir', 25, 1, 0, [('cura malalties',), ('cura estats',), ('cura', 10, 'ferides')], {}),
 ('Majestat divina', 24, 1, 10, [('ritual',), ('àrea',), ('durada',), ('mental', 'control emocional'), ('estat', 'marejat', 3)], {}),
 ("Repel·lir l'antinatural", 20, 3, 8, [('àrea',), ('distància',), ('durada',), ('barrera', 8)], {}),
 ('Restauració', 16, 2, 2, [('durada',), ('tret', 'regeneració', 10), ('estat', 'recuperació', 1)], {}),
 ("Revelar l'èter", 22, 1, 9, [('ritual',), ('àrea',), ('durada',), ('mental', 'llegir'), ('mental', 'projectar')], {}),
 ('Ungir el campió', 9, 1, 10, [('ritual',), ('durada',), ('armadura', 3), ('estat', 'recuperació', 1), ('estat', 'vigilant', 0)], {}),
 ('Animar corser macabre', 22, 1, None, [('ritual',), ('narratiu',), ('invocació', 87)], {}),
 ('Animar gólem de carn', 29, 1, None, [('ritual',), ('narratiu',), ('invocació', 114)], {}),
 ("Animar gos de l'avern", 17, 1, None, [('ritual',), ('narratiu',), ('invocació', 65)], {}),
 ('Animar mortalla voraç', 40, 1, None, [('ritual',), ('narratiu',), ('invocació', 158)], {}),
 ('Bola de foc', 17, 2, 3, [('àrea',), ('distància',), ('dany', 'indirecte', 5, 'foc')], {}),
 ('Con ardent', 12, 1, 2, [('àrea',), ('dany', 'indirecte', 4, 'foc')], {}),
 ('La dalla de la parca', 11, 1, 2, [('durada',), ('dany', 'indirecte', 3, 'fatiga i ferides')], {}),
 ('Descàrrega', 12, 1, 2, [('distància',), ('dany', 'indirecte', 4, 'electricitat')], {}),
 ('Detonar el servent', 20, 1, 10, [('ritual',), ('distància',), ('dany', 'indirecte', 8, 'explosió'), ('estat', 'sagnant', 1)], {}),
 ('Equilibrar la balança', 21, 2, 10, [('ritual',), ('àrea',), ('dany', 'drenatge', 2, 'fatiga i ferides')], {}),
 ('Essència de la brisa', 13, 3, 10, [('ritual',), ('àrea',), ('distància',), ('durada',), ('il·lusió', 3)], {}),
 ('Mot destructiu', 26, 3, 10, [('ritual',), ('distància',), ('dany', 'directe', 9, 'ferides')], {}),
 ('Mot guaridor', 20, 1, 10, [('ritual',), ('distància',), ('cura', 10, 'fatiga o ferides')], {}),
 ('Obrir pany', 20, 1, 12, [('ritual',), ('autoeina', 7)], {}),
 ('Passes de felí', 26, 1, 4, [('usuari',), ('durada',), ('autoeina', 5)], {}),
 ('Polimorfació macabra', 58, 1, 12, [('ritual',), ('distància',), ('durada',), ('transformació', 246)], {}),
 ('Rigor mortis', 17, 3, 5, [('distància',), ('durada',), ('estat', 'immobilitzat', 3), ('estat', 'lent', 3)], {}),
 ('El rostre de la parca', 21, 3, 0, [('àrea',), ('durada',), ('estat', 'acovardit', 2), ('estat', 'immobilitzat', 2)], {}),
 ('Senyor de les mosques', 15, 1, 0, [('àrea',), ('estat', 'atordit', 3), ('estat', 'marejat', 3)], {}),
 ('Set de sang', 16, 1, 10, [('ritual',), ('durada',), ('estat', 'berserc', 2), ('estat', 'recuperació', 4)], {}),
 ("L'urpa de la mort", 22, 4, 0, [('distància',), ('durada',), ('estat', 'atrapat', 2), ('estat', 'sagnant', 2)], {}),
 ('Abatre', 10, 1, 0, [('distància',), ('estat', 'abatut', 2)], {}),
 ('Accelerar', 12, 3, 0, [('usuari',), ('durada',), ('estat', 'ràpid', 2), ('estat', 'recuperació', 1)], {}),
 ('Cicatritzar', 7, 1, 0, [('cura', 4, 'fatiga o ferides')], {}),
 ('Enllaç mental', 10, 2, 5, [('durada',), ('mental', 'llegir'), ('mental', 'projectar')], {}),
 ('Imperatiu', 15, 3, 5, [('distància',), ('durada',), ('mental', 'suggestió')], {}),
 ('Llançament', 13, 1, 0, [('distància',), ('estat', 'llançat', 5)], {}),
 ('Matar màquina', 14, 2, 5, [('autoeina', 5)], {}),
 ('Ment sobre matèria', 20, 2, 0, [('distància',), ('durada',), ('telecinesi', 'alfa')], {}),
 ('Negar el dany', 15, 1, 0, [('reacció',), ('usuari',), ('ègida', 15)], {}),
 ('Pas al costat', 23, 1, 3, [('reacció',), ('usuari',), ('translocació', 'translocació', 'mitjana')], {}),
 ('Projectil', 20, 1, 0, [('distància',), ('telecinesi', 'beta')], {}),
 ('Sonda mental', 10, 2, 5, [('distància',), ('durada',), ('mental', 'llegir')], {}),
 ('Subjugar', 15, 3, 5, [('distància',), ('durada',), ('mental', 'control emocional')], {}),
 ("L'aleteig de la grua", 13, 1, 0, [('àrea',), ('estat', 'atordit', 0), ('estat', 'empès', 2)], {}),
 ("L'anticipació del colibrí", 12, 1, 1, [('usuari',), ('durada',), ('eina', 3), ('estat', 'vigilant', 0)], {}),
 ("L'armadura del queloni", 15, 1, 0, [('reacció',), ('usuari',), ('armadura', 10)], {}),
 ('Circulació del Qi', 16, 2, 0, [('durada',), ('estat', 'recuperació', 4)], {}),
 ("La cogitació de l'asceta", 15, 1, 12, [('ritual',), ('usuari',), ('autoeina', 7)], {}),
 ('Dansa del cel', 9, 1, 3, [('usuari',), ('durada',), ('tret', 'levitar', 15)], {}),
 ('La fugida del pop', 25, 2, 6, [('àrea',), ('durada',), ('replicació', '<1kg', 'monomaterial')], {}),
 ('Inspirar el yang', 13, 2, 2, [('usuari',), ('durada',), ('tret', 'regeneració', 10), ('estat', 'recuperació', 2)], {}),
 ('La intuïció del bodhisattva', 10, 1, 10, [('ritual',), ('distància',), ('durada',), ('mental', 'llegir')], {}),
 ('La ira del drac', 10, 3, 0, [('usuari',), ('durada',), ('estat', 'berserc', 0), ('estat', 'ràpid', 2)], {}),
 ("Les mans d'en Miyagi", 13, 1, 10, [('ritual',), ('cura', 11, 'fatiga o ferides')], {}),
 ('La mirada de la cobra', 8, 1, 0, [('durada',), ('estat', 'marejat', 2)], {}),
 ('La mossegada del sol', 16, 2, 0, [('àrea',), ('durada',), ('estat', 'atordit', 3)], {}),
 ('Projecció del Qi', 26, 2, 2, [('distància',), ('dany', 'directe', 5, 'ferides')], {}),
 ('Puny de drac', 12, 1, 0, [('dany', 'indirecte', 7, 'foc')], {}),
 ('Puny explosiu', 15, 1, 2, [('àrea',), ('dany', 'indirecte', 5, 'explosió')], {}),
 ('El toc de la sangonera', 12, 2, 0, [('durada',), ('estat', 'sagnant', 2)], {}),
 ("L'ull del tigre", 19, 3, 1, [('eina', 2), ('dany', 'directe', 4, 'fatiga o ferides')], {}),
 ('La velocitat del vent', 22, 2, 3, [('usuari',), ('durada',), ('eina', 3), ('estat', 'ràpid', 2), ('tret', 'incansable', 10)], {}),
]
